apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  # Base64 encoded secrets
  jwt-secret: c2VjdXJlaXQtand0LXNlY3JldC1rZXk= # This is "secureit-jwt-secret-key" encoded
  password-encryption-secret: cGFzc3dvcmQtZW5jcnlwdGlvbi1zZWNyZXQta2V5LXNlY3VyZS0yMDI0= # This is "password-encryption-secret-key-secure-2024" encoded