# ConfigMap for auth-server properties
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-server-config
data:
  # Spring Boot configuration properties
  application.properties: |
    # Application name
    spring.application.name=auth-server

    # Database configuration - shares the same DB as the backend
    spring.datasource.url=jdbc:mysql://mysql:3306/password_manager
    spring.datasource.username=root
    spring.datasource.password=root
    spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

    # JPA/Hibernate settings
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.show-sql=true

    # Server configuration
    server.port=8080
    
    # Eureka configuration
    eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
    
    # JWT Configuration
    jwt.secret=${JWT_SECRET}
    jwt.expiration=86400000
    
    # Actuator endpoints for monitoring
    management.endpoints.web.exposure.include=*
    management.endpoint.health.show-details=always
    management.endpoint.prometheus.enabled=true
    management.metrics.export.prometheus.enabled=true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server
  labels:
    app: auth-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-server
  template:
    metadata:
      labels:
        app: auth-server
    spec:
      containers:
      - name: auth-server
        image: auth-server:latest # Matches the image built in local-deployment.sh
        imagePullPolicy: Never # For local development
        ports:
        - containerPort: 8080 # Auth server application port
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql:3306/password_manager" # Internal K8s service name for MySQL
        - name: SPRING_DATASOURCE_USERNAME
          value: "root" # Assuming root user for MySQL
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets # Reference the central secret
              key: db-password  # Key for the DB password
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets # Reference the central secret
              key: jwt-secret   # Key for the JWT secret
        - name: SPRING_APPLICATION_NAME
          value: "auth-server"
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://eureka-server:8761/eureka/" # Internal K8s service name for Eureka
        readinessProbe:
          httpGet:
            path: /actuator/health # Assuming actuator is enabled
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: auth-server
spec:
  selector:
    app: auth-server
  ports:
  - protocol: TCP
    port: 8080       # Service port
    targetPort: 8080 # Container port
    nodePort: 30082  # Expose on NodePort for direct access
  type: NodePort # Use NodePort to match local-deployment.sh output