# ConfigMap for Eureka Server properties
apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-server-config
data:
  # Spring Boot configuration properties
  application.properties: |
    # Application name
    spring.application.name=eureka-server
    
    # Server configuration
    server.port=8761
    
    # Eureka specific configurations
    eureka.client.register-with-eureka=false
    eureka.client.fetch-registry=false
    
    # Actuator endpoints for monitoring
    management.endpoints.web.exposure.include=*
    management.endpoint.health.show-details=always
---
# Eureka Server Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
spec:
  selector:
    matchLabels:
      app: eureka-server
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          image: eureka-server:latest
          imagePullPolicy: Never # For local development
          ports:
            - containerPort: 8761
          env:
            - name: SPRING_CONFIG_LOCATION
              value: "/app/config/application.properties"
          volumeMounts:
            - name: config-volume
              mountPath: /app/config/application.properties
              subPath: application.properties
          readinessProbe:
            tcpSocket:
              port: 8761
            initialDelaySeconds: 20
            periodSeconds: 5
      volumes:
        - name: config-volume
          configMap:
            name: eureka-server-config
---
# Eureka Server Service
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
spec:
  selector:
    app: eureka-server
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
      nodePort: 30761
  type: NodePort