apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: secureit-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: secureit.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
      - path: /api/auth
        pathType: Prefix
        backend:
          service:
            name: auth-server
            port:
              number: 8080
      - path: /api/jwt
        pathType: Prefix
        backend:
          service:
            name: auth-server
            port:
              number: 8080
      - path: /api/passwords
        pathType: Prefix
        backend:
          service:
            name: pmbackend
            port:
              number: 8080
      - path: /api/users
        pathType: Prefix
        backend:
          service:
            name: pmbackend
            port:
              number: 8080
      - path: /eureka
        pathType: Prefix
        backend:
          service:
            name: eureka-server
            port:
              number: 8761
