# Eureka Spring Boot Application Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
        - name: eureka
          image: pmeureka:latest
          imagePullPolicy: Never # For local development
          ports:
            - containerPort: 8761
          env:
            - name: SPRING_CONFIG_LOCATION
              value: "classpath:/application.properties" # or adjust this path as needed
          readinessProbe:
            tcpSocket:
              port: 8761
            initialDelaySeconds: 10
            periodSeconds: 5

---
# Eureka Service for internal communication
apiVersion: v1
kind: Service
metadata:
  name: eureka
  namespace: default

spec:
  selector:
    app: eureka
  ports:
    - protocol: TCP
      port: 8761 # Service port
      targetPort: 8761 # Container's exposed port
  type: ClusterIP
