# Eureka Spring Boot Application Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
        - name: eureka
          image: eureka-server:latest
          imagePullPolicy: Never # For local development
          ports:
            - containerPort: 8761
          env:
            - name: SPRING_APPLICATION_NAME
              value: "eureka-server"
            - name: SERVER_PORT
              value: "8761"
            - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
              value: "false"
            - name: EUREKA_CLIENT_FETCH_REGISTRY
              value: "false"
            - name: EUREKA_SERVER_ENABLE_SELF_PRESERVATION
              value: "false"
          readinessProbe:
            tcpSocket:
              port: 8761
            initialDelaySeconds: 10
            periodSeconds: 5

---
# Eureka Service for internal communication
apiVersion: v1
kind: Service
metadata:
  name: eureka
  namespace: default

spec:
  selector:
    app: eureka
  ports:
    - protocol: TCP
      port: 8761 # Service port
      targetPort: 8761 # Container's exposed port
      nodePort: 30761
  type: NodePort
